global:
  domain: argocd.ayyystew.com

configs:
  params:
    server.insecure: true   # SSL terminated at ingress-nginx, not ArgoCD

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true
