---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZM3dH5/iN+ommftXNju/Ex08NvIy6ofSL7ETxp/+xeTjxM6QPoxdT5tBMEyfvcaNk2K9YaogFL2+hB6ofdCEdOpqOLIqX1EbZk/CQmYfLkblKgggu6baubun9Be2rS78rWki1t/GYFcWIUV7o+Zk9FVCHnKQTo5nPiE6xlnsdAUg+T15xcJP3fly/rPkQ9kw/EKGXVyQTKchw3kgXuDaMCmMNC+1vAnkk9Qd1JmhXXdu5xcWrzw7TRD59gg32MHNsD1ZCYK/ZCKQSxT9l7OcyvzqWZKRSQK6vj9v61YcTGC/Ov3Po6A73QDQqGFuRPFmXGNbUzAQAb893mesERgY9swWa/2Y9uZz0ujWVExMboSMweiMsKXTcOrHhgFI5tv1rNQbjzDWa34bk4wZGHJVbgTrQRtf+p8I0qFAlehuX2cjKYgVYPlYo6zmui3tga6gbZ5yfYqeWcO60Pw2Ua7U+WS3gLWeqg0z7hAbuizJFL+mgOtjbtLAoACN3wPIQlAfBg6xt72kJpePSeTKqjA+cBAxTwsWiUDFEI/8Mk24F3vEve7LQbQIdyBiOqL13SzyN2Ij9knDpdtjV3SCWeiewDDgokoVcnoMzMHWMhjt1r/5aLOhazdmzj9cH33ZKQzabzV3qo98bq0pRySmKHwYSF3YYvlijCrP1OYdMVqV2peSSWFx71X1bIT79hUT0pZF/N/RUnmag9otUtbNUWcAhziB5Q3g70o5mNPJDGxOWtH94fvyhqSy283tC5NYTBIJUklv5HA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
