---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAOFqd+50g7/3+0uF/UUpTyR0OhxBFkgiNWZV2czVNvXAadVMql+6+MTqHc5ryrPcIZc4Gusot3ak0viM5FG3/Ioga0QMEVG/9okr0ravyOmb3sY9w5y79Kx1kX7GNxEEzE9QXuYs+oVybo4r6/5K0HoZqpd8wPkc8jIXL1bOVl/xuYSISLSAwaKb8EV6xSRWDp4d6vPOwxpr6XKbmcOhFat+IQTVEovo5Vaezv8TidXcq9bqizfYpB9I0hRuiqZ1SprJpHSnZ4b5QaSi3CkZ4XM9fJ2KfDL4LpZU/fSUCIjNI6Xcz50zqHrK37dv2r2kugkbbqrYh5ezgj67GbZf1XJUnbw2SRULmqzD1JjgOWmVy4mp6BO7MjYIbYSqcekn0rBI1gnxZrxpfWmvlosZGK+r2bSM1ZnG007Nzj3t0RHyvnAH5k4Ml9/PeMd342RTf8JesmRtEp2VsJwQMXQLDWsjt9ZEj3GZsY44revcU/xsQo1X4owHV1bkSbX39z6ZZR7phJNcezOlUb5AmGCfll1p26CTpd1lpE0p7zxzHp0WVqLpiPemWDTGYg8rld0X3e7r9YqNE3m7ZvV/UqOcUfZ3nHVhecBFhEt6InkJ1xkKo0bt4zyAz174nCecAnp/JT0wt4//eYAzj5ZmqlQ/IBboPiGw/u7a+ZNUVm2jw29BQD4+xaenKtmDspQRukL4TU/fO0c0ptb02C7+PgEguzV0MzehetOQS7QwnlfWCNzUt2XFUYdLicZbIZsOWDocXUNZokEg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
