---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCGn9Mv9JcThszZygUkbh8j6Ze5wK3gJabD0ZFH5JZNUDVa6AeVvY8mU35BZfwKizA5gnB2CRTNvxgpgPSzlVt/Tf2y2qESdEppavGzB94OIUy8WYG/fNRvd7UbwO48xhHtJh0X2PfIbKTOUkzv36Pqupeb6k2bIK40T3BT97l+WhRm1DEx3Fs91BUGpG3+zI4Kj0cTX+Xlc+ciuA/bh8+XpjoD/CKitWBLi/5Rl8y+pwLmqS9nqj7/UnpgLcRu/fKKfGQ8n7Lyp/SQ76Uf0APPHPszyNxef8wMjrGe5h+sFvBlC7MaS/VhUVsHO0t8srSzOhSAas1z4WNEWYSmuwmjEzDyEP+4iYA7frP+QklpQZctJRpZO1E1/zf0qGF9UNVeQKgcyAVbfrSHhYPyW3vReDNy8BJXURi0ObDw6VNMyps6JTnCyauZqUji/PU29gp2oG17U7Ow/W2RLPvmp2gWMdsfqSQilkg0tfvYDTfbo8YmBZY2EgUz3x840jb7DHXCUk45XbSNyMr2CDxhNAOzjmQf8057Bkq0vQsWjNtCkq0z9XTSBVJo0RLgRZQaiO0Beh25RfV6hENznCuNHXAmnodmIn975b5Twxw2fdkJiCpKTPq0/8uMYRFuRUhG6gPpxveQVqcaav609iVEoQccUVLKar4dupThAdjZy9BwXObS93PbQEuhJXH/exhaI9LYCwVtU9NBPs3ZM/y6yH+RRe86M7iag9gzVfqK8y8UgKuDZBJPm8zhSPI0pz3ChflqJ6mU/g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
