---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAtT1Eqz2mnjShJSmeIU8SUVZV5dWlupUoFH8MQspVSrEQpb6nxWMwu+m/lcG7padaumHzrTutgjsNHh/84snk69w1EOuxgrsteg+H473bVZ+tdVtD6112pdTHEzv9L9k0cOT1eaTAAs/FsDc5Rt4rwb4r42qb5BpkCnbEs/NlB6W4VJBTqBZjhQakCQrYio+QFSqzemd2pdrFtP+DNMeKSG0mA2Sg26nRVQHSu+EASONn6t4e45Sh64xQVICdnt3PK0xwdXQGzPw2BnWapHPn8/Y+yZfhfHQ78g1izcugEQN3k3ot8mScmIXAHassWBEWJQVAw4lTpCpDe7sT8tSs6jHbO5vhCFWlOqVbtuXqfLTKwneTx5zawUQLLWZLCeDpG4fow7q8PxKAVyY0eVe1O379Iep25gzql4//8gox2nV9UwMoTisRlnJYbYP1lCejk7sLUB6llGb+nxSSZsmtiy/9hsR4dTjdOIwE0eAUoq9QpotNOLu2yy/VFMYm+PHlAtrqlqSG3Ok4cJDLSucShkDwvXqjB7I/IX833aFEzNwRlEe/loCXAzYcyPf8HaCh27obdZxzkFj4DQCv8PQOv3CtD18xWzpuu9U53Ix1jn7yrEoAGMtAznqawDI4VCzWhF+CZBnA9mRXyoCVuF7F6RzgxGEGvdGfcJSWatM6670eRnOX5YA6Vua8vrhUaMwF5ZQLHoZVCpHQEaLI=
    admin-user: AgCbApC46HyIHXkPsZNnCrYUEljnnDwzFPwS+tJu0k6da3tutivR3+kUmXIlur6sq4ZgqWIY9a3VJUvP6UY2S/1mHuEKIO3RbDaqdRJx03Z8Eh+9sERzUsOdWhPptMMGo4zDvMnVqdJQ+JmECjhwYFMGN4hB+X9HfNuMHM+XVQhMRudU3VBb506OVm+zcJvxyzKUYmdP3XHu52sYbyixUo9tPG60S04NmgAWsYHHlupDErYvmyltRJSHn5t7a/1PotChRHdt6YAv0i949gaDVsOYJJUaGEEAzOQI8Qk2ge0K2eUhFzlC83FzWafPRC1HPCcad+h+8hmGgkb+zgazf54/jDf2k2Fq2Q1d5CrP2mdZB83ga65qBy5qZlP7QSD7sl/2UWvy0gNJRIu2TVNshziLWVVzbtWfcLfq4z/3Sbl4fF3f2TgmDAG2GSN2sPSRwImpgZbgn2MAo/XaWNxBSqSDtWofdYdGnuPYXYNyHsINbhDx99LMp8OlzUz1a6j3uudmylGWi0s8Lef6MJHmlFIl3nS3/x4yshWxaLhdKNxiz7kfQ6iXjM+ieCFyq1N42Wb3JbaHU+o6hxXvP7v858X2a+m7Uv54FINZuJWKGBniZtHKVFXYVKBFcFTJ2OXB/teL2ZkOx9YYqpWFx2f7h254gCh9D3aAPpq4B1it9bl7BIveUPWJYkmIc2fsU0VYny91ObOfMw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
