---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8BmVr5qRv8RVXEZbnGFuRf9eHqWZh+eBs6gAF7I0e1wQwHsrcmt506y0fjMnTsTtfOI6JdjENp+jGNvK9tt+SqFeimdH+bA7I8+oNHxdu9bdFzH5CTKvEMUiIuZK6ePj1QL49DWeUns6f8JTaTpNooJfrMydxgVRJXUn5GYnNCXq1Pp2miwTOcWvRVWhX41w6XMOgls470ugCfmx4SWJff5ADqnS6buVngkSb7ujOFLaJg1+Y7zJyD9jr/ukpdjTTO70v+9r8HUFrIo3KF++GU8aCVZaPVxnZl6Pyv6WBehd1IGW4pcVE7emKWHdFLBD1pZr7HRxz/+1+03LfCt6Gjpm0iFD01wxoWi3lhBKwLfia2QuCB1reDBTb0ODmMPg2gXjWvEpUwCZlqYXBVMv03N7SoRJA+aji6CxeG139pXcHkRiQcGg/kbS76aNZGhmqpQLEFmurezJScLzUP/pNpSkOB8Xe948ggesG8Fphb4Hrxg56FB/ywAxocudShU1n1Rb9AmSFgVjoLl3NRPegmLk6E9SjN66fFrMPVdEkacdnasqvKYSB4pXQdFBEcsXRBZSa/UPQm/iLglmYGrZ/RWWbrpvYyLvCfLSKdIoSl/tER7vTg+4tSS6aw3bx2YNadpvz43j/zvgo6qv5M9aKu+CG7Sci3en3PK60OLbna8Zbb/fGkM3WNMcP58tlgkNOAeBN6SyQ4/tpINg=
    admin-user: AgAECgxPUIAYCRaHYqZ9RLO6ctXx20KXWP4y2RsgNPcbud3yP0zwmeDzbB1dLCtHiAPz8C7d8SzQJdk1UdJVup1z02bonTpNj4i+eKO7tNUvOVh+D+hGu2tScBEDbIUUl/Z0gRX09RTqOQRT5swy+SXmv3FT+HZ1SQ5twenVhLXm09qcla+i91gwwupzvbqaI+Sb6avryxNuGRilnf1tDNVJ0WHDI/JoWH/FIDaRa8YX+JFuo/NmQQXO6/hpkOCk1okmcTzqmkFLZegUSnPZgQxUraB2Qf/OHtPSv3yObx2/TuPoKyyn2dCOt8IUShJz/wMY1vsgYhA9kj8hSHxgQhvT2CRGw0HTKTTNireP9qY1OJ8sLlLkCw8wR3il/d7g2qIW0yPHl21tq/qyf7hzVsK2K8IM0bmgQM6oShzMoVWIa3JaCMsHagcnlXpd3IYLD2kNBXuI6TC/F6wyEcu9MJiUiNMknVP+sdF/Afj8ol6MWAkJ6WqtkUl5bZFtiNuIyXWEilteaRLHH00Vf5UVAjlIf4GLWi/x+NhGZC+cPnFVaVDYf4FcHWVfRwcCOfBlb/TKDPePHFCMcyOY6gff3S77uSh/op8GMGs4gvvJCIfgWSQBm7jhfY5396ALFGqEeS75UxonFndIm3XFcE0pn9ztGu0vp//Bw++vLRSgjOAtRRl9OIFALaeeniq0wNRjVeDtfjJ5Sw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
