---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBMcKxmbssgJ3sIxxXAPnOZW18sHZHjc3MY8BYulVBVD6dCb5B3ftIYySXFNM6VUfb9r4upbZYnM3LdvG3xXGCfObQSoby7xKFIN22ZGKvxjdCFMv94qOv8qz6TNRdtIsEa/Wp/kW45A17M8XBrRdTz/GugvwOABlHhLK/N/wE/IsO1DjKp9gi8hnfUf965uxkbvQjLWzYktzheiBcj8M3JRi7hyJmaj5xFXQePXlPHQ5pDDgocU60OP2f5yYXjnRrK0+dFHjiofTrbDxB2dPpOOX/Zyg7kzArUfgPdnWZol8VJmXh2wj5Q7rUlQ053e2keU3vTNNfQVknvy/DJbIKCWlFYdUWxHTDZ9QE1KMOXiTiWA9sD+kqP5jD4CNJSZ7/INPQ4vSJBxs5wcR4rMzbJLvZPgRKGJqu7Svyo2o+peM7FErAPp/lCDHQsUEG5oOrEU9ewFCRLBr38DXHuAMqNgcUr9Tr66y3AFoah/xwzxRuSQdFnOxOUkroJPqdnfgK71/Lde8yeuZ6TuZ0xprVzFc9pMJ7E1trFqroKS5E/DEUWCF+vsyrd5OCKp1kThhk2PvdH5iIYopqthot+OCCtUNnfk4ZGV0Z8OpO183XUPWGskJ8MQdcHYfr3zpAQG9i/hToD3nLL8jcJk5zGSu8CbOzlcG6VkwwbETKDSsYiHH/yvsZclAA3lukp14C9zvKHIG4DL5jSZPIZeMc=
    admin-user: AgCAuIcxkmrSJITDDcv35HK5erenjW8LMlMnnTS6pKO+n4vds16ZItj2iMsnKXh1QGCigECV3u2Ogeff+CEFoksbeZ52jkj3S+a00Y9yXPjZCTAJW7ZUomwPNF4uXyR1ITa3yQnio4J2fQzA5fAKHPtrgA1B+Gw4Dj9BYEkmH9KG+mKqaf7c42BUiM6urlpRwfasp2FLRH/ulpmQZkDbCTg6aU9tKjjdtSvh3I0BayUs3VxMNBS9FvjlqrUFzw5zVVclsOk/PRNu2X5Ulw6rP8wD8+orTcS5mKZovEWdrfYvnrrCcd0N/B/h5fWTAajk4a11KFlN7Pvov5Upx+WUYcFs8PHHARVNmGJ/Xux6CI1jcdMFoB/+gT1TS1CFHQrY7C3ly+Ut3x+vm5G8HM8JSCfSlZ/3kX5dUC1SXCRaSD6h++pLK3x6BKjNqy7/SupwsM8YN6n6QOwtS/K1sscTih9B2rAIpr5uXZEJ6scR5Y4qIbJp9lkrgizcRK+C2DtWA3V6TKt65Ip+G6kf/nkeS+VkaJAatJnw9JLFZmF3GuPoNPfJPvu00SPao2Pa/t5uT1ZEpPuuGSMmx2sBHZ0Lt3fgbbSwTsKFxN4rPV0tl+lxWH29fS9dTBZkJhnwtx8dcm6RaeK1dEUk/St3Eb2B3GzlEyLLSVXKXq27h0tYsNx5gsqApvvH5FnjI6dgyd/2nMdmdcU7+A==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
